/* eslint-disable @next/next/no-css-tags */
import Head from "next/head";

import WhatsappButton from "@/components/whatsappButton";

import { Container } from "./elements";

const MainWrapper = ({ children }: any) => {
  return (
    <>
      <Head>
        <title>WeWork | Office Space and Workspace Solutions</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
        <link
          rel="preload"
          href="//www-static.wework.com/apercu/apercu.css"
          as="style"
        />

        <link
          rel="stylesheet"
          href="//www-static.wework.com/apercu/apercu.css"
        />

        <link
          rel="stylesheet"
          href="//www-static.wework.com/apercu/apercu_mono.css"
        />

        <link
          rel="stylesheet"
          href="/vanilla-assets/stylesheets/vendor.bc11321946874dd2d91a972acd538f05.css"
        />
      </Head>
      <Container>
        <WhatsappButton />
        {children}
      </Container>
    </>
  );
};

export default MainWrapper;
