import Head from "next/head";

import linksNavbarInfo from "@/data/linksNavbar.json";

import Cintillo from "@/layouts/cintillo";
import Navbar from "@/layouts/navbar";
import WhatsappButton from "@/components/whatsappButton";

import { Container } from "./elements";

const MainWrapper = ({ children }: any) => {
  return (
    <>
      <Head>
        <title>WeWork | Office Space and Workspace Solutions</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <Cintillo />
      <Navbar linkInfo={linksNavbarInfo} />
      <WhatsappButton />
      <Container>{children}</Container>
    </>
  );
};

export default MainWrapper;
